# Generated by Django 3.2.3 on 2021-05-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheets',
            name='sheet_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
